# Generated by cpputils-cmake.
include /home/seb/Git/Lima/build/camera/princeton/CMakeFiles/princeton.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES} -I/usr/src/linux/include -DNDEBUG -S ${CHK_SOURCES}
